baseURL = "https://pdfta2.netlify.com/"
languageCode = "en-us"
title = "PDFTA | Data Consulting"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "PDFTA | About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "PDFTA | Service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "PDFTA | Blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "PDFTA | Contact"
        url     = "contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "PDFTA Data Consulting"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HERE AT PDFTA WE SPECIALISE IN"
        description = "WITH YEARS EXPERIENCE IN DATA PRODUCTS, WITH A FOCUS ON DELIVERING VALUE AND DEPLOYING TO PRODUCTION WE USE ALL SORTS OF SKILLS"
        btn     = false
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "DATA SCIENCE"
        [[params.banner.flipText]]
            title   = "DATA ANALYSIS"
        [[params.banner.flipText]]
            title   = "DASHBOARDING"
        [[params.banner.flipText]]
            title   = "DATA ENGINEERING"
        [[params.banner.flipText]]
            title   = "MACHINE LEARNING IN PRODUCTION"
        [[params.banner.flipText]]
            title   = "END-TO-END DATA PRODUCTS"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT US"
        content = "Here at PDFTA we believe that industry has high expectations from low hanging fruit. Often we see a huge amount of success from small projects. We also develop our own products internally."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "Get in touch"
        content = "We are always happy to have a chat over coffee."
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Case Studies"
        subtitle= "Explore some of our previous projects."

    