baseURL = "https://www.pdfta.com/"
languageCode = "en-us"
title = "PDFTA | Data Consulting"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "PDFTA | Blog"
        url     = "blog"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "PDFTA Data Consulting"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "EMPOWER YOUR BUSINESS THROUGH DATA"
        description = "MAXIMISE VALUE FROM YOUR DATA"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT US"
        content = "Here at PDFTA we believe that industry has high expectations from low hanging fruit. Often we see a huge amount of success from small projects. We also develop our own products internally."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "info@pdfta.com"
        content = "We are always happy to have a chat over coffee."
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Our Work"

    